spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，springboot2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，springboot2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1

#mongoDB数据库配置信息
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: article
#      password:
#      username:


  #文件上传地址信息
  servlet:
   multipart:
     enabled: true
     max-file-size: 1000MB
     # 单个文件的最大值
     max-request-size: 1000MB
     # 上传文件总的最大值
  boot:
    admin:
      client:
        url: http://localhost:9879

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/



