server:
  port: 8889
spring:
  application:
    name: admin-server
  mail:
    host: smtp.qq.com
    username: 1309095142@qq.com
    password: qhcnoncjdyfvbabd
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  boot:
    admin:
      notify:
        mail:
          from: ${spring.mail.username}
          to: xchen1@tcl.com
          #          ignore-changes: UNKNOWN:UP
      #          ignore-changes:
      #            -
      #              "*:UP" #从任何状态到up状态都不要发邮件通知
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: admin-server #注册id

turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  app-config: community-service #设置需要监控的serviceId


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/
