#
spring:
  profiles:
    active: dev
  mvc:
#    view:
#      prefix: webapp/WEB-INF/jsp/
#      suffix: .jsp

#    static-path-pattern: /static/**
  main:
    allow-bean-definition-overriding: true
  application:
    name: service

swagger:
  base-package: com.article.service.mvc

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/


#mybatis:
#  type-aliases-package: com.tcl.community.test.entity
#  mapper-locations: classpath:com.tcl.community.mapper/*.xml

server:
  port: 8991


