spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    url: jdbc:mysql://10.92.33.136:3306/oneaccount           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: tcl@123                                  # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数
      initial-size: 50                               # 初始化提供的连接数
      max-total: 5000                                  # 最大的连接数
      max-wait-millis: 20                          # 等待连接获取的最大超时时间
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，springboot2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，springboot2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
#mongoDB数据库配置信息
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
#      password:
#      username:


#  #文件上传地址信息
#  servlet:
#   multipart:
#     enabled: true
#     max-file-size: 100MB
#     # 单个文件的最大值
#     max-request-size: 10MB
#     # 上传文件总的最大值



eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/



